### ISSUE TITLE
Ensure cross-platform compatibility

### ISSUE THREAD

**Issue by sdhutchins** [datasnakes/renv#22]
- [ ] Test functionality on Windows particularly finding paths.

**Comment by grabear** [comment]
For the hackathon, the primary objective is to get this working on Linux, but if we can add Windows compatibility as well then that would be pretty nice.

**Comment by sdhutchins** [comment]
Yeah, I think it'll be one of those things we get to post-hackseq barring some miraculous coding lol

**Comment by grabear** [comment]
Closing for now to develop Linux.
